project:
  type: book
  output-dir: docs

book:
  title: "Mass Spec Academy"
  favicon: figs/favicon.png
  page-navigation: true
  image: figs/ExtendedGeometryLineDrawing.svg
  output-file: "Mass Spectrometry Book"
  site-url: https://massspec.academy/
  repo-url: https://github.com/EARTHTIME/MassSpecAcademy/
  repo-actions: [issue, edit]
  chapters: 
    - index.qmd
    - part: "Background"
      href: overview.qmd
      chapters: 
      - template_chapter.qmd
      - text: "Concept Review"
        href: background.qmd
      - ion_sources.qmd
    - part: "Contributors"
      chapters:
      - about/aboutme_cox.qmd
      - about/aboutme_mclean.qmd 
      - about/aboutme_arkula.qmd 
      - about/aboutme_cruz-uribe.qmd 
      - about/aboutme_dutton.qmd 
      - about/aboutme_ickert.qmd 
      - about/aboutme_lloyd.qmd 
      - about/aboutme_panahi.qmd 
      - about/aboutme_piasecki.qmd 
      - about/aboutme_runyon.qmd 
      - about/aboutme_souders.qmd 
      - about/aboutme_tremblay.qmd 
    - part: "Mass Spectrometry Overview"
      chapters: 
      - mass_spec_history.qmd
      - mass_spec_design.qmd
      - mass_spec_types.qmd
    - part: "Mass Spectrometer Design"
      chapters: 
      - ion_source_design.qmd
      - mass_analyzer_design.qmd
      - detector_design.qmd
      - vacuum_systems.qmd
    - part: "Mass Spectrometry Techniques"
      chapters: 
      - NGMS.qmd
      - TIMS.qmd
      - ICPMS.qmd
      - SIMS.qmd
      - Oribtrap.qmd
    - part: "Analytical Considerations"
      chapters: 
      - baselines.qmd
      - peak_tails_abundance_sensitivity.qmd
    - part: "Isotope Systems"
      chapters:
      - Ar_Ar.qmd
      - U_Pb.qmd
      - U_Th_He.qmd
      - Re-Os.qmd
    - part: "Interpreting Data"
      chapters:
      - basic_stats_refresher.qmd
    - references.qmd
  appendices: 
    - contributing.qmd
    - citing.qmd
  navbar:
    logo: figs/MSA_logo.png
    right:
      - text: "Contribute"
        href: contributing.qmd


bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 3
    toc-title: "Contents"
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^https:\/\/EARTHTIME\.github\.io.*$'
    code-fold: true
  pdf: default
  
number-depth: 3