---
title: "Types of mass spectrometer"
---

## Overview

A variety of different types of mass spectrometers exist. In detail, the type of mass spectrometer is defined by the combination of an ion source, one more type of mass analyzer, and one or more type of detector. Different combinations of these three components will give you a different type of mass spectrometer. Since each type of mass spectrometer typically only has one type of ion source, we have organized this section at a high level by ion source, and then by type of mass analyzer or analyzers. We do not delve into detector arrays at this stage; while in practice the detector configuration matters for specific mass spectrometer applications, in terms of defining mass spectrometer 'types' this is the least important characteristic.

## Thermal Ionization

Thermal ionization sources are basically only used in one type of mass spectrometer: a Thermal Ionization Mass Spectrometer, or TIMS. It's pretty straightforward: the ions are generated by thermal ionization, and then the ions are accelerated through a magnetic sector to achieve momentum to charge separation. Boom! It's that easy. The beautiful simplicity of the TIMS is why this was the first mass spectrometer to come into existence. In the geosciences, TIMS is most commonly used for high-precision and high-temperature geochronology (e.g., zircon U-Pb geochronology) and geochemistry (e.g., W isotopes). Before the advent of ICP-MS technology, TIMS was also commonly used for trace element analyses. 

## Electron Impact Source

Mass spectrometers with electron impact sources are used to analyze materials or samples that, upon being let into the mass spectrometer, are already in a gaseous state. The type of mass spectrometer that has an electron impact source is then defined by the type (or types) of mass analyzer the gaseous ions encounter after being accelerated away from the ion source.

### Sector Field Mass Spectrometers

Sector field mass spectrometers use magnetic sectors as their primary mass analyzer. 

#### Static Volume Mass Spectrometers, Including Noble Gas Mass Spectrometers

Static volume mass spectrometers consist of an electron impact source and a magnetic sector mass analyzer. Importantly, with these mass spectrometers measurements are made 'statically', i.e., the volume of the mass spectrometer is not being pumped on by vacuum pumps during the analysis. Static volume mass spectrometers are very commonly utilized to analyze noble gas isotopes and other gases (e.g., N isotopes) extracted from solid materials where there is a finite, comparably small amount of gas that would be consumed too quickly if the mass spectrometer volume was being pumped on during the analysis. This type of instrument is commonly used for geochronology using noble gas systems (e.g., $^{40}$Ar$^{39}$Ar).

#### Isotope Ratio Mass Spectrometers

<!---
Someone who knows more about IRMS than me should write this yay!!
--->

### Quadrupoles

Gases ionized with electron impact source can also have quadrupoles as their analyzer.

#### Residual Gas Analyzers

#### Gas Chromatograph Mass Spectrometer

### Electric Field Sector Instruments

#### Ion Traps

#### Orbitraps

## Secondary Impact Source

### Accelerator Mass Spectrometers

### Secodnary Ion Mass Spectrometers (SIMS and NanoSIMS)

### TOF-SIMS

## Inductively Copuled Plasma Source

### Quadrupole ICPs

#### ICP-Q-MS

#### ICP-TOF

#### ICP-SF-MS (often just referred to as ICP-MS)

### Tandem mass spectrometers (ICP-MS/MS)

#### Two mass analyzers + collision reaction cell

## Electrospray Ionization

### Orbitrap

### Quadrupole

### TOF
