# TIMS {#sec-TIMS}

## TIMS designs {#sec-TIMS-designs}

There's a list of ingredients in the components chapters. Here is the general recipe for a TIMS:

- sources are mostly the same (some brand differences, one vs. several filaments)
- short vs. long ion optics lens stacks
- just a magnet
- magnet + ESA
- a mix of faradays and/or electron multiplication systems
- other components: retardation filter, zoom optics
- high vacuum (turbo backed by dry scroll/rotary/piston)
- high vacuum bits: ion pumps, TSPs, ion gauge.
- 

## Making ions {#sec-TIMS-making-ions}

- how we get samples on filaments. emitters, sample loading schemes (triple filament with an evaporation filament and an ionization filament). Silica gel + phosphoric or graphite or tantalum oxide or etc. 
- What determines which of these schemes gets used? Work function, first ionization potential, other concerns (electrochemistry of glasses). Dark arts and magic.
- Langmuir and Langmuir-Saha equation, filament temperature, controls on ionization efficiency vs. ionization rate. Note we should ignore Carlson here.
- positive and negative ions (osmium and boron?)
- Warmup, stepwise heating, evaporation and fractionation of sample. Considerations in how to load and adjust the temperature.
- Periodic table with positive vs. negative ions, another with first ionization potentials. 
- Cavity sources

## Steering ions {#sec-TIMS-source-ion-optics}

- Lens stacks are mostly the same, accelerating voltages near 8-10 kV. 
- Defining slit sizes are in the 0.3 mm range.
- TIMS tend to use low resolution

## Analyzers {#sec-TIMS-analyzers}

- Magnetic sector, usually with extended geometry. 
- Laminated vs. wrapped electromagnet. Speed vs. cooling.
- ESF sometimes (OG S54)
- More magnets are possible, not often used outside nuclear operations

## Detectors {#sec-TIMS-detectors}

A TIMS instrument can have a single collector, or more commonly a multi-collector setup (MC-TIMS) with multiple Faraday cups or ion detectors to make simultaneous, precise isotope ratio measurements. There are MC-TIMS instruments commercially available with one or multiple SEMs or Dalys to measure lower intensity beams. While early TIMS instruments had detectors in fixed positions, the development of movable detectors has enabled increased flexibility to analyze a variety of different isotope systems. 

- Faradays often large, 1 mm opening slit, movable, equipped with suppressors and porous graphite insert. [note from AD: not sure if this detail is needed here or if already covered in detector section]
- Electron multipliers (one or many), analog or ion counting


### Amplification systems {#sec-TIMS-amplifiers}

- Resistive vs. Capacitive Trans-Impedence Amplifiers (see also NGMS)
- $10^{10}$ to $10^{13}$ $\Omega$ amplifiers for resistive.
- ATONA and older capacitive systems.

## TIMS methods {#sec-TIMS-methods}

- Dynamic vs. static methods
- Single collector methods

## Vacuum systems {#sec-TIMS-vacuum-systems}

- TIMS need high vacuum in general
- Source has a turbo backed by a dry rough pump.
- Analyzer side has ion pumps, plus maybe a TSP.
- Pirani and ion gauge on the source, separate ion gauge on the analyzer.
- High vacuum considerations for TIMS sources --- samples must be "smoked" or dried down, no low-temp volatile compounds, 

## Other components {#sec-TIMS-other-components}

- retardation lens useful for peak tailing problems
- zoom optics makes for multidynamic measurements without peak top position compromise

## Advantages and Disadvantages of TIMS {#sec-TIMS-Adv-Disadv}

TIMS has several advantages relative to some of the other types of mass spectrometers.  High precision isotope ratio measurements can be generative with abundance sensitivity in the ppb range because it produces ions with a limited range of energies. TIMS also confers nearly 100% transmission of ions from the source to the collector. The ability to ionize samples at different temperatues allow for multiple isotope systems to be measured from a single filament in sequence, e.g., U and Th or U and Pb, and that this process can be easily automated. In contrast to some other sources such as a plasma source instrument, the ionization source is very stable; hence mass fractionation is more stable so that standard-sample bracketing is not necessary to capture drift. Both positive and negative ions can be produced, conferring flexibility to measure a wider range of isotope systems. Additionally, with TIMS there is no interference introduced from the source such as with Ar plasma sources where reactions between the plasma gas and the sample can produce a range of products in the high-temperature plasma environment, despite the general non-reactivity of this noble gas.  From a practical perspective, MC-TIMS instruments are less costly to run than MC-ICP-MS instruments, which consume large quantities of Ar gas that add up quickly for an instrument that sees a lot of use and they generally require more electricity than TIMS instruments due to the RF generator.

Some disadvantages of using TIMS is the time-intensive nature of the entire process, including filament loading through to stepwise heating and analysis.  In general, ionization efficiency is < 1% and some elements have ionization efficiencies that are so low that they are not well-suited to TIMS.


## Troubleshooting TIMS 

- Causes of no ion beams.